[theme]
primaryColor = "#2563eb"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#131316"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 20

[browser]
gatherUsageStats = false
